# Generated by Django 5.1 on 2024-11-21 01:45

import appWeb.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0006_servicio_carrito_itemcarrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarrito',
            name='usuario',
            field=models.ForeignKey(default=appWeb.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
