# Generated by Django 5.1 on 2024-11-21 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0007_itemcarrito_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcarrito',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='carrito',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carrito', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itemcarrito',
            name='carrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='appWeb.carrito'),
        ),
    ]
