# Generated by Django 5.1 on 2024-11-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0009_servicio_categoria_alter_servicio_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='categoria',
            field=models.CharField(choices=[('INSTALACION', 'Instalación'), ('MANTENIMIENTO', 'Mantenimiento'), ('SOPORTE_TECNICO', 'Soporte_Técnico')], default='INSTALACION', max_length=50),
        ),
    ]
