# Generated by Django 5.1 on 2024-11-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0010_alter_servicio_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='categoria',
            field=models.CharField(choices=[('INSTALACION', 'Instalación'), ('MANTENIMIENTO', 'Mantenimiento'), ('SOPORTETECNICO', 'Soporte Técnico')], default='INSTALACION', max_length=50),
        ),
    ]
