# Generated by Django 5.1 on 2024-11-22 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0011_alter_servicio_categoria'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarrito',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
