# Generated by Django 5.1 on 2024-11-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0014_remove_itemcarrito_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='favorito',
            field=models.BooleanField(default=False),
        ),
    ]
