# Generated by Django 5.1 on 2024-11-27 21:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0016_sobrenosotros_pregunta'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseña',
            name='valoracion',
            field=models.PositiveIntegerField(default=3, help_text='La valoración debe estar entre 1 y 5.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
