# Generated by Django 5.1 on 2024-11-27 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0017_reseña_valoracion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pregunta',
            old_name='pregunta',
            new_name='contenido',
        ),
        migrations.RenameField(
            model_name='pregunta',
            old_name='fecha_creacion',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='respuesta',
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
